# Generated by Django 5.0.10 on 2025-08-03 02:09

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_alter_equityvalue_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equityvalue',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'InterDay'), (2, 'Daily'), (3, 'Monthly')], default=3, help_text='Select a Account'),
        ),
        migrations.AlterField(
            model_name='equityvalue',
            name='value_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1961, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2100, 1, 1))], verbose_name='Value Date'),
        ),
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
