# Generated by Django 5.0.10 on 2025-08-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0033_equityvalue_value_type_alter_equityvalue_value_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equityvalue',
            unique_together={('equity', 'value_date', 'value_type')},
        ),
    ]
