# Generated by Django 5.0.10 on 2025-08-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0034_alter_equityvalue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='split_fix',
            field=models.BooleanField(default=False),
        ),
    ]
