# Generated by Django 4.2 on 2024-04-23 18:58

from django.db import migrations, models
import django.db.models.deletion

from expenses.models import Category, SubCategory


def create_reference_equities(apps, schema_editor):
    initial_data = {
        'Food': ['Grocery', 'TakeOut', 'Dinning'],
        'Utilities': ['Water', 'Electricity', 'Heat', 'Telecom'],
        'Housing': ['Maintenance', 'Mortgage/Rent', 'Appliances/Furniture', 'Insurance', 'Taxes', 'Other'],
        'Healthcare': ['Medical', 'Dental', 'Insurance', 'Other'],
        'Recreation': ['Events', 'Camping', 'Golf', 'Computers/Tech', 'Streaming', 'Other'],
        'Transportation': ['Fuel', 'Maintenance', 'Lease/Purchase', 'Insurance', 'Parking/Tolls', 'Fees', 'Public/Rental'],
        'Personal Care': ['Beauty', 'Fitness', 'Clothing', 'Other'],
        'Alcohol': ['Alcohol'],
        'Other': ['Education', 'Unknown']
    }

    for key in initial_data:
        category = Category.objects.create(name=key)
        for subcategory in initial_data[key]:
            SubCategory.objects.create(name=subcategory, category=category)


class Migration(migrations.Migration):

    initial = True

    dependencies = [('expenses', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_reference_equities)
    ]
