# Generated by Django 4.2 on 2024-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
