# Generated by Django 4.2 on 2024-05-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_item_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amortized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='expenses.item'),
        ),
    ]
