# Generated by Django 4.2 on 2024-06-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_item_amortized'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_from', to='expenses.item'),
        ),
    ]
