# Generated by Django 5.0.9 on 2024-11-04 20:01

from django.db import migrations, models
from expenses.models import Category, SubCategory


def create_reference_equities(apps, schema_editor):
    initial_data = {
        'Income': ['Salary', 'Commissions', 'Pensions', 'Government Programs', 'Investments', 'Refunds'],
        'Other': ['Taxes',]
    }

    for key in initial_data:
        try:
            category = Category.objects.get(name=key)
        except Category.DoesNotExist:
            category = Category.objects.create(name=key)

        for subcategory in initial_data[key]:
            try:
                subcategory = SubCategory.objects.get(name=subcategory, category=category)
            except SubCategory.DoesNotExist:
                SubCategory.objects.create(name=subcategory, category=category)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_item_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='income',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_reference_equities)

    ]
