# Generated by Django 5.0.10 on 2025-03-28 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='SubCategory'),
        ),
    ]
