# Generated by Django 5.0.10 on 2025-06-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_item_source_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('-', '-----'), ('starts', 'Starts With'), ('ends', 'Ends With'), ('contains', 'Contains')], max_length=8),
        ),
    ]
