# Generated by Django 5.0.10 on 2026-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_itemtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtag',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='expenses.itemtag'),
        ),
    ]
