# Generated by Django 5.0.9 on 2024-10-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='worth',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
