# Generated by Django 5.0.10 on 2026-07-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_country_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.IntegerField(choices=[(10, 'Admin'), (20, 'Adjusted'), (25, 'Generated'), (30, 'API'), (35, 'Reconciled'), (40, 'Uploaded'), (45, 'Imported'), (50, 'Manual'), (60, 'Estimated')], default=60)),
                ('us_to_can', models.DecimalField(decimal_places=2, max_digits=4)),
                ('can_to_us', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.IntegerField(choices=[(10, 'Admin'), (20, 'Adjusted'), (25, 'Generated'), (30, 'API'), (35, 'Reconciled'), (40, 'Uploaded'), (45, 'Imported'), (50, 'Manual'), (60, 'Estimated')], default=60)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inflation', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
