# Generated by Django 5.0.10 on 2024-12-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profile_goals_remove_profile_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='CA', max_length=2),
            preserve_default=False,
        ),
    ]
