# Generated by Django 5.0.10 on 2025-02-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='fail_length',
            field=models.IntegerField(blank=True, default=10800, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='fail_reason',
            field=models.CharField(default='Manual Suspension', max_length=132),
        ),
        migrations.AlterField(
            model_name='url',
            name='base',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
    ]
