# Generated by Django 5.0.10 on 2025-02-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_url_fail_length_url_fail_reason_alter_url_base'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='API',
        ),
    ]
