# Generated by Django 5.2.8 on 2026-05-19 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (45, 'IMPORT'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
                ('value', models.DecimalField(decimal_places=3, help_text='The value on this date', max_digits=10)),
                ('balance', models.BooleanField(default=False, help_text='Set when used to force a balance on a particular Day - Used to override deposit values')),
                ('note', models.TextField(blank=True, help_text='Arbitrary text to describe where this funding came from/went to', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name to display for this Account/Portfolio', max_length=64)),
                ('currency', models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', max_length=3)),
                ('account_name', models.CharField(blank=True, help_text='Specific Account Name, use in imports from your trading account', max_length=128, null=True)),
                ('managed', models.BooleanField(default=True, help_text='Set when Dividends will be automatically reinvested')),
                ('acct_type', models.CharField(blank=True, choices=[('Trading', 'Equity/ETF/Mutual Fund'), ('Cash', 'Bank Accounts'), ('Value', 'Value Account')], default='Trading', max_length=10, null=True)),
                ('closed', models.DateField(blank=True, help_text='Date when account was closed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('basecash_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wealth.basecash')),
            ],
            options={
                'abstract': False,
            },
            bases=('wealth.basecash',),
        ),
        migrations.CreateModel(
            name='ValueBalance',
            fields=[
                ('basecash_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wealth.basecash')),
            ],
            options={
                'abstract': False,
            },
            bases=('wealth.basecash',),
        ),
        migrations.AddField(
            model_name='basecash',
            name='account',
            field=models.ForeignKey(help_text='The account this is linked to', on_delete=django.db.models.deletion.CASCADE, to='wealth.account'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('symbol', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Trading symbol')),
                ('country', models.CharField(default='CA', max_length=2, verbose_name='Country hosting the investment')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Investments Full Name')),
                ('inv_type', models.CharField(blank=True, choices=[('Trading', 'Equity/ETF/Mutual Fund'), ('Cash', 'Bank Accounts'), ('Value', 'Value Account'), ('Funding', "Account's actual funding")], default='Trading', max_length=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', max_length=3, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('deactivated_date', models.DateField(blank=True, null=True, verbose_name='Date this investment was de-listed or deactivated')),
                ('searchable', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('closed', models.DateField(blank=True, help_text='The date an investment is de-listed', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (45, 'IMPORT'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('day_scope', models.BooleanField(default=False)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='wealth.investment')),
            ],
            options={
                'unique_together': {('date', 'investment', 'day_scope')},
            },
        ),
        migrations.AddField(
            model_name='basecash',
            name='investment',
            field=models.ForeignKey(help_text='The investment this is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='wealth.investment'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name to display for this Account/Portfolio', max_length=64)),
                ('currency', models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wealth.portfolio'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='The date of position')),
                ('scope', models.CharField(default='month', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='The quantity of units on this date', max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, help_text='The avg price of each unit on this date', max_digits=10)),
                ('account', models.ForeignKey(help_text='The account this is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='wealth.account')),
                ('investment', models.ForeignKey(help_text='The investment this is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='wealth.investment')),
            ],
            options={
                'unique_together': {('date', 'account', 'investment', 'scope')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='positions',
            field=models.ManyToManyField(through='wealth.Position', to='wealth.investment'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (45, 'IMPORT'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='The quantity of units', max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, help_text='The price of each unit (and the time of purchase', max_digits=10)),
                ('buy', models.BooleanField(default=True, help_text='Set to True if this is a BUY and False if it is a SELL')),
                ('note', models.TextField(blank=True, help_text='Arbitrary text to describe where this Transaction came from/went to', null=True)),
                ('account', models.ForeignKey(help_text='The account this is linked to', on_delete=django.db.models.deletion.CASCADE, to='wealth.account')),
                ('investment', models.ForeignKey(help_text='The investment this is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wealth.investment')),
                ('cash_acct', models.ForeignKey(blank=True, help_text='Cash Flow Record', null=True, on_delete=django.db.models.deletion.CASCADE, to='wealth.cashflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DividendAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altered', models.BooleanField(default=False)),
                ('dividend', models.ForeignKey(help_text='This Dividend record', on_delete=django.db.models.deletion.CASCADE, to='wealth.dividend')),
                ('cash_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wealth.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('basecash_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wealth.basecash')),
                ('cash_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wealth.cashflow')),
            ],
            options={
                'abstract': False,
            },
            bases=('wealth.basecash',),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_name', 'user')},
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (45, 'IMPORT'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
                ('close_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('open_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('day_scope', models.BooleanField(default=False)),
                ('split_fixed', models.BooleanField(default=False)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='wealth.investment')),
            ],
            options={
                'unique_together': {('date', 'investment', 'day_scope')},
            },
        ),
    ]
