# Generated by Django 5.2.8 on 2026-05-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cash_acct',
            new_name='cash_record',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buy',
        ),
    ]
