# Generated by Django 5.0.10 on 2026-09-15 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('date', 'account', 'investment')},
        ),
        migrations.AlterField(
            model_name='accountinvestment',
            name='open_date',
            field=models.DateField(default=datetime.date(2026, 9, 15)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='accountinvestment',
            unique_together={('account', 'investment')},
        ),
        migrations.RemoveField(
            model_name='position',
            name='scope',
        ),
    ]
