# Generated by Django 5.0.10 on 2026-09-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0002_alter_position_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvestment',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
