# Generated by Django 5.2.8 on 2026-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0002_rename_cash_acct_transaction_cash_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecash',
            name='source',
            field=models.IntegerField(choices=[(10, 'Admin'), (20, 'Adjusted'), (30, 'API'), (35, 'Reconciled'), (40, 'Uploaded'), (45, 'Imported'), (50, 'Manual'), (60, 'Estimated')], default=60),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='source',
            field=models.IntegerField(choices=[(10, 'Admin'), (20, 'Adjusted'), (30, 'API'), (35, 'Reconciled'), (40, 'Uploaded'), (45, 'Imported'), (50, 'Manual'), (60, 'Estimated')], default=60),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.IntegerField(choices=[(10, 'Admin'), (20, 'Adjusted'), (30, 'API'), (35, 'Reconciled'), (40, 'Uploaded'), (45, 'Imported'), (50, 'Manual'), (60, 'Estimated')], default=60),
        ),
        migrations.AlterField(
            model_name='value',
            name='source',
            field=models.IntegerField(choices=[(10, 'Admin'), (20, 'Adjusted'), (30, 'API'), (35, 'Reconciled'), (40, 'Uploaded'), (45, 'Imported'), (50, 'Manual'), (60, 'Estimated')], default=60),
        ),
    ]
