# Generated by Django 5.0.10 on 2026-09-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0003_alter_accountinvestment_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendamount',
            name='dividend',
            field=models.ForeignKey(help_text='This Value/Dividend record', on_delete=django.db.models.deletion.CASCADE, to='wealth.value'),
        ),
    ]
