# Generated by Django 5.0.9 on 2024-09-11 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('us_to_can', models.FloatField()),
                ('can_to_us', models.FloatField()),
                ('source', models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('inflation', models.FloatField()),
                ('source', models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, verbose_name='Trading symbol')),
                ('region', models.CharField(default='Canada', max_length=10)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Equities Full Name')),
                ('equity_type', models.CharField(blank=True, choices=[('Equity', 'Equity/Stock'), ('ETF', 'Exchange Traded Fund'), ('MF', 'Mutual Fund'), ('MM', 'Money Market')], max_length=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='USD', max_length=3, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('deactived_date', models.DateField(blank=True, null=True)),
                ('searchable', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('symbol', 'region')},
            },
        ),
        migrations.CreateModel(
            name='EquityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, verbose_name='Trading symbol')),
                ('region', models.CharField(default='Canada', max_length=10)),
                ('name', models.TextField()),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
            ],
        ),
        migrations.CreateModel(
            name='EquityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_date', models.DateField(null=True, verbose_name='Recorded Date')),
                ('date', models.DateField(verbose_name='Normalized Date')),
                ('value', models.FloatField()),
                ('event_type', models.TextField(choices=[('Dividend', 'Dividend'), ('SplitAD', 'Stock Split with Adjusted Dividends'), ('Split', 'Stock Split')], max_length=10)),
                ('source', models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=10)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
            ],
        ),
        migrations.CreateModel(
            name='EquityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_date', models.DateField(null=True, verbose_name='Recorded Date')),
                ('date', models.DateField(verbose_name='Normalized Date')),
                ('price', models.FloatField()),
                ('source', models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique name for this account', max_length=128)),
                ('currency', models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='USD', max_length=3, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique name for this account', max_length=128)),
                ('account_name', models.CharField(blank=True, help_text='The name as imported', max_length=128, null=True, unique=True)),
                ('managed', models.BooleanField(default=True)),
                ('currency', models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='USD', max_length=3, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, help_text='Date this account was Closed', null=True)),
                ('last_import', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.portfolio')),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_date', models.DateField(null=True, verbose_name='Transaction Date')),
                ('date', models.DateField(verbose_name='Normalized Date')),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('xa_action', models.IntegerField(choices=[(1, 'Fund'), (2, 'Buy'), (3, 'Reinvested Dividend'), (4, 'Sell'), (6, 'Interest'), (5, 'Redeem'), (7, 'Sold for Fees')], help_text='Select a Account')),
                ('estimated', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.account')),
                ('equity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
