# Generated by Django 4.2.5 on 2023-09-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('buy_action', models.BooleanField(default=True)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='members',
            field=models.ManyToManyField(through='stocks.Transaction', to='stocks.equity'),
        ),
        migrations.CreateModel(
            name='EquityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
            ],
        ),
        migrations.CreateModel(
            name='EquityDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
            ],
        ),
    ]
