# Generated by Django 4.2.7 on 2023-11-15 16:17

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Equities Full Name')),
                ('symbol', models.CharField(max_length=32, verbose_name='Ticker name used when trading this equity')),
                ('equity_type', models.CharField(blank=True, choices=[('Equity', 'Equity/Stock'), ('ETF', 'Exchange Traded Fund'), ('MF', 'Mutual Fund')], max_length=10)),
                ('region', models.CharField(choices=[('TRT', 'Toronto'), ('', 'United States')], default='TRT', max_length=10, verbose_name='Region where this is traded')),
                ('currency', models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', max_length=3)),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique name for this portfolio', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity', models.TextField(choices=())),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('buy_action', models.BooleanField(default=True)),
                ('equity_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='EquityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
            ],
        ),
        migrations.CreateModel(
            name='EquityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('event_type', models.TextField(choices=[('Dividend', 'Dividend'), ('SplitAD', 'Stock Split with Adjusted Dividends'), ('Split', 'Stock Split')], max_length=10)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity')),
            ],
        ),
    ]
