# Generated by Django 4.2 on 2024-03-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityalias',
            name='region',
            field=models.CharField(default='Canada', max_length=10),
        ),
        migrations.AlterField(
            model_name='equity',
            name='currency',
            field=models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='equity',
            name='region',
            field=models.CharField(default='Canada', max_length=10),
        ),
        migrations.AlterField(
            model_name='equity',
            name='searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equityalias',
            name='symbol',
            field=models.CharField(max_length=32, verbose_name='Trading symbol'),
        ),
        migrations.AlterField(
            model_name='equityevent',
            name='source',
            field=models.IntegerField(choices=[(1, 'MANUAL'), (2, 'ADJUSTED'), (3, 'API'), (4, 'UPLOAD'), (5, 'ESTIMATE')], default=1),
        ),
        migrations.AlterField(
            model_name='equityvalue',
            name='source',
            field=models.IntegerField(choices=[(1, 'MANUAL'), (2, 'ADJUSTED'), (3, 'API'), (4, 'UPLOAD'), (5, 'ESTIMATE')], default=1),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.PositiveIntegerField(choices=[(1, 'MANUAL'), (2, 'ADJUSTED'), (3, 'API'), (4, 'UPLOAD'), (5, 'ESTIMATE')], default=5),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='source',
            field=models.PositiveIntegerField(choices=[(1, 'MANUAL'), (2, 'ADJUSTED'), (3, 'API'), (4, 'UPLOAD'), (5, 'ESTIMATE')], default=5),
        ),
        migrations.AlterUniqueTogether(
            name='equity',
            unique_together={('symbol', 'region')},
        ),
    ]
