# Generated by Django 4.2 on 2024-04-23 18:58

from django.db import migrations, models
import django.db.models.deletion

from stocks.models import Equity


def create_reference_equities(apps, schema_editor):
    for equity in ['VFV', 'XEI', 'ZGQ']:
        e = Equity(symbol=equity)
        e.save(update=False)


class Migration(migrations.Migration):

    initial = False

    dependencies = [('stocks', '0001_initial')]

    operations = [
        migrations.RunPython(create_reference_equities)
    ]
