# Generated by Django 4.2 on 2024-05-20 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='Enter a unique name for this portfolio', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('name', 'user')},
        ),
    ]
