# Generated by Django 5.0.9 on 2024-09-12 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_name', 'user')},
        ),
    ]
