# Generated by Django 5.0.9 on 2024-09-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_account_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.portfolio'),
        ),
    ]
