# Generated by Django 5.0.9 on 2024-09-18 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_account_portfolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cost',
            new_name='_cost',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='dividends',
            new_name='_dividends',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='end',
            new_name='_end',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='start',
            new_name='_start',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='value',
            new_name='_value',
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'user')},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='xa_action',
            field=models.IntegerField(choices=[(1, 'Fund'), (2, 'Buy'), (3, 'Reinvested Dividend'), (4, 'Sell'), (6, 'Dividends/Interest'), (5, 'Redeem'), (7, 'Sold for Fees'), (8, 'Transferred In'), (9, 'Transferred Out')], help_text='Select a Account'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
    ]
