# Generated by Django 4.2 on 2024-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_transaction_xa_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='real_date',
            field=models.DateField(null=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Normalized Date'),
        ),
    ]
