# Generated by Django 5.0.9 on 2024-09-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_rename_cost_account__cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acccount_name',
            field=models.CharField(blank=True, help_text='The name as imported', max_length=128, null=True, unique=True),
        ),
    ]
