# Generated by Django 4.2 on 2024-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_transaction_real_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='deactived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equityevent',
            name='source',
            field=models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=10),
        ),
        migrations.AlterField(
            model_name='equityvalue',
            name='source',
            field=models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='source',
            field=models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60),
        ),
    ]
