# Generated by Django 5.0.9 on 2024-09-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_equity_deactived_date_alter_equityevent_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='xa_action',
            field=models.IntegerField(choices=[(1, 'Fund'), (2, 'Buy'), (3, 'Reinvested Dividend'), (4, 'Sell'), (6, 'Interest'), (5, 'Redeem'), (7, 'Sold for Fees')], help_text='Select a Portfolio'),
        ),
    ]
