# Generated by Django 5.0.9 on 2024-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_transaction_estimated_alter_transaction_xa_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityevent',
            name='real_date',
            field=models.DateField(null=True, verbose_name='Recorded Date'),
        ),
        migrations.AddField(
            model_name='equityvalue',
            name='real_date',
            field=models.DateField(null=True, verbose_name='Recorded Date'),
        ),
        migrations.AlterField(
            model_name='equityevent',
            name='date',
            field=models.DateField(verbose_name='Normalized Date'),
        ),
        migrations.AlterField(
            model_name='equityvalue',
            name='date',
            field=models.DateField(verbose_name='Normalized Date'),
        ),
    ]
