# Generated by Django 5.0.9 on 2024-10-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.TextField(choices=[('Investment', 'Investment'), ('Holding', 'Holding')], default='Investment', max_length=12),
        ),
    ]
