# Generated by Django 5.0.9 on 2024-10-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
