# Generated by Django 5.0.9 on 2024-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_transaction_currency_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='equity_type',
            field=models.CharField(blank=True, choices=[('Equity', 'Equity/ETF'), ('ETF', 'Exchange Traded Fund'), ('MF', 'Mutual Fund'), ('MM', 'Value Account')], max_length=10, null=True),
        ),
    ]
