# Generated by Django 5.0.9 on 2024-11-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_equity_equity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, help_text='The name as imported', max_length=128, null=True),
        ),
    ]
