# Generated by Django 5.0.10 on 2024-12-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_alter_account_managed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.TextField(choices=[('Investment', 'Investment'), ('Bank', 'Bank'), ('Value', 'Value')], default='Investment', max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='The name to display for this Account/Portfolio', max_length=128),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='The name to display for this Account/Portfolio', max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='xa_action',
            field=models.IntegerField(choices=[(1, 'Fund'), (2, 'Buy'), (3, 'Reinvested Dividend'), (4, 'Sell'), (6, 'Dividends/Interest'), (5, 'Redeem'), (7, 'Sold for Fees'), (8, 'Transferred In'), (9, 'Transferred Out'), (10, 'Value')], help_text='Select a Account'),
        ),
        migrations.CreateModel(
            name='AccountFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Funds Full Name')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.account')),
            ],
            options={
                'unique_together': {('name', 'account')},
            },
        ),
        migrations.CreateModel(
            name='AccountFundValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_date', models.DateField(null=True, verbose_name='Recorded Date')),
                ('date', models.DateField(verbose_name='Normalized Date')),
                ('value', models.FloatField()),
                ('source', models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.accountfund')),
            ],
            options={
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
