# Generated by Django 5.0.10 on 2024-12-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_account_account_type_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.accountfund'),
        ),
    ]
