# Generated by Django 5.0.10 on 2025-01-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_transaction_fund'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountFundValue',
            new_name='FundValue',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fund',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.TextField(choices=[('Investment', 'Investment'), ('Cash', 'Bank'), ('Value', 'Value')], default='Investment', max_length=12),
        ),
        migrations.AlterField(
            model_name='equity',
            name='equity_type',
            field=models.CharField(blank=True, choices=[('Equity', 'Equity/ETF'), ('Cash', 'Bank Accounts'), ('Value', 'Value Account')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='xa_action',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Buy'), (3, 'Reinvested Dividend'), (4, 'Sell'), (6, 'Dividends/Interest'), (5, 'Withdraw'), (7, 'Sold for Fees'), (8, 'Transferred In'), (9, 'Transferred Out'), (10, 'Value')], help_text='Select a Account'),
        ),
        migrations.DeleteModel(
            name='AccountFund',
        ),
    ]
