# Generated by Django 5.0.10 on 2025-02-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_alter_equityvalue_equity_alter_fundvalue_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityevent',
            name='source',
            field=models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=10),
        ),
        migrations.AlterField(
            model_name='equityvalue',
            name='source',
            field=models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60),
        ),
        migrations.AlterField(
            model_name='fundvalue',
            name='source',
            field=models.IntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=50),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='source',
            field=models.PositiveIntegerField(choices=[(10, 'ADMIN'), (20, 'ADJUSTED'), (30, 'API'), (35, 'RECONCILED'), (40, 'UPLOAD'), (50, 'USER'), (60, 'ESTIMATE')], default=60),
        ),
    ]
