# Generated by Django 5.0.10 on 2025-02-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_alter_equityevent_source_alter_equityvalue_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='equity_type',
            field=models.CharField(blank=True, choices=[('Equity', 'Equity/ETF'), ('Cash', 'Bank Accounts'), ('Value', 'Value Account')], default='Equity', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equityevent',
            name='event_type',
            field=models.TextField(choices=[('Dividend', 'Dividend'), ('SplitAD', 'Stock Split with Adjusted Dividends'), ('Split', 'Stock Split with Dividends and Price Adjusted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='equityvalue',
            name='equity',
            field=models.ForeignKey(limit_choices_to={'equity_type': 'Equity'}, on_delete=django.db.models.deletion.CASCADE, to='stocks.equity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='xa_action',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Buy'), (3, 'Reinvested Dividend'), (4, 'Sell'), (6, 'Dividends/Interest'), (5, 'Withdraw'), (7, 'Fees Paid'), (8, 'Transferred In'), (9, 'Transferred Out'), (10, 'Value'), (11, 'Balance')], help_text='Select a Account'),
        ),
    ]
