# Generated by Django 5.0.10 on 2025-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_alter_equity_equity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityevent',
            name='api',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='equityvalue',
            name='api',
            field=models.IntegerField(default=99),
        ),
    ]
