# Generated by Django 5.0.10 on 2025-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_equityevent_api_equityvalue_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityevent',
            name='split_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equityvalue',
            name='split_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equityevent',
            name='event_type',
            field=models.TextField(choices=[('Dividend', 'Dividend'), ('Split', 'Stock Split Dividend and Pricing will be adjusted based on API used')], max_length=10),
        ),
    ]
