# Generated by Django 5.0.10 on 2025-03-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_alter_equity_currency_alter_equityevent_real_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundvalue',
            old_name='fund',
            new_name='equity',
        ),
        migrations.AlterUniqueTogether(
            name='equityvalue',
            unique_together={('equity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='fundvalue',
            unique_together={('equity', 'date')},
        ),
    ]
