# Generated by Django 5.0.10 on 2025-04-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_rename_fund_fundvalue_equity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stocks.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('stocks.account',),
        ),
    ]
