# Generated by Django 5.0.10 on 2025-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_investmentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='derived_type',
            field=models.CharField(default='foo', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
