# Generated by Django 5.0.10 on 2025-04-04 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_account_derived_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stocks.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('stocks.account',),
        ),
        migrations.CreateModel(
            name='ValueAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stocks.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('stocks.account',),
        ),
        migrations.RemoveField(
            model_name='account',
            name='derived_type',
        ),
    ]
