# Generated by Django 5.0.10 on 2025-07-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_rename_deactived_date_equity_deactivated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='deactivated_date',
            new_name='deactived_date',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='alternate_symbol',
        ),
        migrations.AlterField(
            model_name='equity',
            name='equity_type',
            field=models.CharField(blank=True, choices=[('Equity', 'Equity/ETF'), ('Cash', 'Bank Accounts'), ('Value', 'Value Account')], default='Equity', max_length=10, null=True),
        ),
    ]
