# Generated by Django 5.0.10 on 2025-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_rename_deactivated_date_equity_deactived_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='deactived_date',
            new_name='deactivated_date',
        ),
        migrations.AlterField(
            model_name='equity',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
