# Generated by Django 5.0.10 on 2025-07-08 14:45

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_rename_deactived_date_equity_deactivated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityvalue',
            name='value_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1961, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2100, 1, 1))], verbose_name='Recorded Date'),
        ),
    ]
