# Generated by Django 4.2 on 2024-04-23 18:58

from datetime import datetime
from django.db import migrations
from django.utils import timezone

from stocks.models import EquityValue


def update_datetime(apps, schema_editor):
    for ev in EquityValue.objects.all():
        convert_time = ev.real_date if ev.real_date else ev.date
        convert_time = datetime(convert_time.year, convert_time.month, convert_time.day)
        ev.value_date = timezone.make_aware(convert_time, timezone.get_current_timezone())
        ev.save()


class Migration(migrations.Migration):

    initial = False

    dependencies = [('stocks', '0030_equityvalue_value_date')]

    operations = [
       migrations.RunPython(update_datetime)
    ]
