# Generated by Django 5.0.10 on 2025-07-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0031_FixDateTime_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equityvalue',
            unique_together={('equity', 'value_date')},
        ),
    ]
